# Generated by Django 4.2.29 on 2026-03-03 18:46

from django.db import migrations, models
import hrms.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=hrms.models.generate_employee_id, editable=False, max_length=20, unique=True),
        ),
    ]
